### ISSUE TITLE
additional embed information

### ISSUE THREAD

**Issue by aczrimuru** [AnonDev-org/discord-tickets_transcripts#2]
**Is your feature request related to a problem? Please describe.**
I receive a lot of transcripts from different categories, searching it using discord search wouldn't filter from what category it's from.
**Describe the solution you'd like**
Would like to suggest adding additional embed information which the category would also be included on the transcript log

**Describe alternatives you've considered**
I haven't considered any other options ticket id wouldn't suffice.

**Additional context**
None

**Comment by anondev-sudo** [comment]
Opened PR
