### ISSUE TITLE
Failed to send ticket transcript to the ticket creator

### ISSUE THREAD

**Issue by dlmckenzie2004** [AnonDev-org/discord-tickets_transcripts#5]
**Describe the bug**
Ticket transcript does not send to ticket creator

**To reproduce**
When send_to_user is configured to true, type is set to attachment and /settings set log_messages:True

User closes ticket and error is sent in console and transcript is not sent to ticket creator (the transcript still successfully sends in guild channel ID)

[WARN] Failed to send ticket transcript to the ticket creator
2021-11-09 18:03:11 [ERROR] ReferenceError: transcript is not defined
    at TicketManager.<anonymous> (/root/bot/node_modules/AnonDev-org.discord-tickets_transcripts/index.js:271:15)
    at runMicrotasks (<anonymous>)

**Expected behaviour**
Transcript sends to both ticket creator and guild channel as configured.

**Comment by anondev-sudo** [comment]
Yes, I am aware of this bug. Will try to fix it when I will have time.

**Comment by anondev-sudo** [comment]
Does someone know what's wrong there?

**Comment by anondev-sudo** [comment]
Fixed in the new version - https://github.com/AnonDev-org/discord-tickets_transcripts/releases/tag/1.2.4

**Comment by anondev-sudo** [comment]
Now it should be completely fixed - you can choose if you want to DM the user when ticket was closed and if you want to include also transcript there or not
