### ISSUE TITLE
New hastebin endpoint

### ISSUE THREAD

**Issue by t6c** [AnonDev-org/discord-tickets_transcripts#6]
**Describe the bug**
- Not really a big bug, but hastebin changed their endpoint result in not being able to POST request when using hastebin as transcript type in the config

**Screenshot**
- ![Capture](https://i.imgur.com/n2b48Jx.jpg)
- (also produced an open bug: can not send transcript to users)

**Quick fix...maybe?**
- Fix the code at around line 290+

**Comment by anondev-sudo** [comment]
> (also produced an open bug: can not send transcript to users)

It was reported here https://github.com/AnonDev-org/discord-tickets_transcripts/issues/5

**Comment by anondev-sudo** [comment]
Changed hastebin url to my selfhosted - https://haste.pinglik.eu
